#!/usr/bin/env bash
# World wide web
domain=$1
subdomain=$2
func () {
	con=$1
	ip="$(dig $con.$domain | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
	re="$(dig $con.$domain | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
	echo The subdomain $con is a $re record and points to $ip
	return 0
}
if [ $# == 1 ]
then
	func www
	func lb-01
	func web-01
	func web-02
else
	func $subdomain
fi
