#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
