#!/usr/bin/env bash
# Install Nginx web server
new="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Holberton School" | /var/www/html/index.html
sudo sed -i "35i $new" /etc/nginx/sites-available/default
sudo service nginx restart
