#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 777 /
sudo echo "Holberton School" | tee /var/www/html/index.nginx-debian.html
sudo chmod -R 777 /etc/nginx
sudo sed -i "35i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
