#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get install haproxy -y
sudo chmod 777 /etc/haproxy/
sed -i "$ a frontend firstbalance \n\tbind *:80 \n\tmode http \n\tdefault_backend webs" /etc/haproxy/haproxy.cfg
sed -i "$ a backend webs \n\tbalance roundrobin \n\tmode http \n\tserver 1173-web-01 35.243.187.246:80 check \n\tserver 1173-web-02 3.85.202.216:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
