#!/usr/bin/env bash
# Manage my process
if [ $# != 0 ]
then
	if [ "$@" == start ]
	then
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo $"manage_my_process started"
	fi
	if [ "$@" == stop ]
	then
		rm -rf /var/run/my_process.pid
		echo $"manage_my_process stopped"
		pkill -f manage_my_process
	fi
	if [ "$@" == restart ]
	then
		rm -rf /var/run/my_process.pid
		echo $"manage_my_process restarted"
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
	fi
else
	echo $"Usage: manage_my_process {start|stop|restart}"
fi
