#!/usr/bin/env bash
#Tell the story of passwd
while IFS=":" read -r l1 l2 l3 l4 l5 l6 l7
do
printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$l1" "$l4" "$l6" "$l7" "$l3" "$l2" "$l5"
done < /etc/passwd | (cut -d ":" -f 1,2,3,4,5,6,7)
