#!/usr/bin/env bash
i="0"
while [ $i -le 10 ]
do
        if [ "$i" -eq 9 ]
        then
                echo "Hi"
        else
                echo "Holberton School"
        fi
        i=$((i+1))
done
