#!/usr/bin/env bash
#exist
if [ -e "holbertonschool" ]
then
        echo $"holbertonschool file exists"
        #empty
        if [ -s "holbertonschool" ]
        then
                echo $"holbertonschool file is not empty"
        #not empty
        else
                echo $"holbertonschool file is empty"
        fi
        #regular
        if [ -f "holbertonschool" ]
        then
                echo $"holbertonschool is a regular file"
        fi
#not exist
else
        echo $"holbertonschool file does not exist"
fi
