#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
sudo chomd 777 /etc/nginx/nginx.conf
sed -i "worker_processes/i user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
